#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jul 21 21:51:12 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=COBBLEVERSE - Shaders
