#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Sat Oct 03 20:40:03 KST 2026
alwaysLogTamperWarnings=true
